"""create game_rooms and game_players tables

Revision ID: b3b658444406
Revises: e492ebd2191e
Create Date: 2026-07-11 15:00:05.281182

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3b658444406"
down_revision: str | Sequence[str] | None = "e492ebd2191e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_rooms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("invite_code", sa.String(length=16), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("lobby", "running", "paused", "finished", "archived", name="game_status"),
            nullable=False,
        ),
        sa.Column("settings_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_game_rooms_invite_code"), "game_rooms", ["invite_code"], unique=True)
    op.create_table(
        "game_players",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("network_name", sa.String(length=64), nullable=True),
        sa.Column("network_color", sa.String(length=16), nullable=True),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("net_worth", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("is_ready", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "user_id", name="uq_game_players_game_user"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_players")
    op.drop_index(op.f("ix_game_rooms_invite_code"), table_name="game_rooms")
    op.drop_table("game_rooms")
    # ### end Alembic commands ###
    sa.Enum(name="game_status").drop(op.get_bind(), checkfirst=True)
