"""create game_stations station_fuels financial_transactions and network_name uniqueness

Revision ID: d7cb5b564cfd
Revises: e9eb9674bb81
Create Date: 2026-07-11 18:29:21.154748

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7cb5b564cfd"
down_revision: str | Sequence[str] | None = "e9eb9674bb81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("transaction_type", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("balance_before", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reference_type", sa.String(length=32), nullable=True),
        sa.Column("reference_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["game_players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_stations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("station_template_id", sa.UUID(), nullable=False),
        sa.Column("owner_player_id", sa.UUID(), nullable=True),
        sa.Column("purchase_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("queue_length", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_player_id"],
            ["game_players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["station_template_id"],
            ["station_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "game_id", "station_template_id", name="uq_game_stations_game_template"
        ),
    )
    op.create_table(
        "station_fuels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_station_id", sa.UUID(), nullable=False),
        sa.Column("fuel_type", sa.Enum("ai92", "ai95", "diesel", name="fuel_type"), nullable=False),
        sa.Column("current_liters", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reserved_liters", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("capacity_liters", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("retail_price", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("average_purchase_price", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_station_id"],
            ["game_stations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "game_station_id", "fuel_type", name="uq_station_fuels_station_fuel_type"
        ),
    )
    op.create_unique_constraint(
        "uq_game_players_game_network_name", "game_players", ["game_id", "network_name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_game_players_game_network_name", "game_players", type_="unique")
    op.drop_table("station_fuels")
    op.drop_table("game_stations")
    op.drop_table("financial_transactions")
    # ### end Alembic commands ###
    sa.Enum(name="fuel_type").drop(op.get_bind(), checkfirst=True)
