"""create station_templates and refineries tables

Revision ID: e9eb9674bb81
Revises: b3b658444406
Create Date: 2026-07-11 18:07:50.095914

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9eb9674bb81"
down_revision: str | Sequence[str] | None = "b3b658444406"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refineries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("road_node_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "station_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("osm_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("road_node_id", sa.String(length=64), nullable=True),
        sa.Column("base_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_station_templates_osm_id"), "station_templates", ["osm_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_station_templates_osm_id"), table_name="station_templates")
    op.drop_table("station_templates")
    op.drop_table("refineries")
    # ### end Alembic commands ###
