"""add fuel_sales table and station_fuel price_updated_at

Revision ID: 31a8bcbab8cf
Revises: d7cb5b564cfd
Create Date: 2026-07-11 18:58:29.186788

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "31a8bcbab8cf"
down_revision: str | Sequence[str] | None = "d7cb5b564cfd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

fuel_type_enum = postgresql.ENUM("ai92", "ai95", "diesel", name="fuel_type", create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fuel_sales",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("station_id", sa.UUID(), nullable=False),
        sa.Column("fuel_type", fuel_type_enum, nullable=False),
        sa.Column("liters", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("price_per_liter", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cost_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("profit_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game_rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["game_stations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "station_fuels", sa.Column("price_updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("station_fuels", "price_updated_at")
    op.drop_table("fuel_sales")
    # ### end Alembic commands ###
